# Generated by Django 4.0 on 2021-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_testfunction_clasaprincipala'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasaprincipala',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
