# Generated by Django 4.0 on 2021-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_clasaprincipala_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='date',
            field=models.DateField(),
        ),
    ]
