# Generated by Django 4.0 on 2021-12-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_clasaprincipala_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasaprincipala',
            name='date',
        ),
    ]
