# Generated by Django 4.0 on 2021-12-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_workout_alter_clasaprincipala_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasaprincipala',
            name='counterParticipanti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasaprincipala',
            name='listaParticipanti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
