# Generated by Django 4.0 on 2021-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_clasaprincipala_counterparticipanti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='counterParticipanti',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='listaParticipanti',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
