# Generated by Django 4.0 on 2021-12-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_clasaprincipala_counterparticipanti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasaprincipala',
            options={'ordering': ['oraInceput']},
        ),
        migrations.RenameField(
            model_name='clasaprincipala',
            old_name='durata',
            new_name='oraInceput',
        ),
    ]
