# Generated by Django 4.0 on 2021-12-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_clasaprincipala_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.workout'),
        ),
    ]
