# Generated by Django 4.0 on 2021-12-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_workout_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasaprincipala',
            options={'ordering': ['workout']},
        ),
        migrations.AddField(
            model_name='clasaprincipala',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
