# Generated by Django 4.0 on 2022-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_clasaprincipala_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
