# Generated by Django 4.0 on 2022-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_clasaprincipala_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
