# Generated by Django 4.0 on 2022-01-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_clasaprincipala_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='oraInceput',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.workout'),
        ),
    ]
