# Generated by Django 4.0 on 2022-01-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_clasaprincipala_orainceput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
